// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62rulj0bxAfdfg5uCv7NK71CWYzMAvbs',
    appId: '1:451158197612:web:96ad9a8edb14f89f969f49',
    messagingSenderId: '451158197612',
    projectId: 'hookup-chat-app',
    authDomain: 'hookup-chat-app.firebaseapp.com',
    storageBucket: 'hookup-chat-app.appspot.com',
    measurementId: 'G-34KW4T8WZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzJz4H6Ukax9XUyvuO_0nbpTWLrVZ4k8',
    appId: '1:451158197612:android:1819b19d989e7d89969f49',
    messagingSenderId: '451158197612',
    projectId: 'hookup-chat-app',
    storageBucket: 'hookup-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhqkOB5mW7spnZ6GE6p_12IyRh4GN1AE',
    appId: '1:451158197612:ios:7de53a0d7675ec73969f49',
    messagingSenderId: '451158197612',
    projectId: 'hookup-chat-app',
    storageBucket: 'hookup-chat-app.appspot.com',
    iosClientId: '451158197612-ac8oj631fddc680ogu2tfsq508t611jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hookUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhqkOB5mW7spnZ6GE6p_12IyRh4GN1AE',
    appId: '1:451158197612:ios:7de53a0d7675ec73969f49',
    messagingSenderId: '451158197612',
    projectId: 'hookup-chat-app',
    storageBucket: 'hookup-chat-app.appspot.com',
    iosClientId: '451158197612-ac8oj631fddc680ogu2tfsq508t611jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hookUp',
  );
}
